# Generated by Django 3.1.2 on 2020-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('account_holder', models.CharField(max_length=128)),
                ('group_number', models.CharField(max_length=32)),
                ('account_number', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=32)),
                ('coverage', models.FloatField(default=0.0)),
            ],
        ),
    ]
