# Generated by Django 3.1.2 on 2020-11-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance',
            new_name='PInsurance',
        ),
    ]
