# Generated by Django 3.1.2 on 2020-11-12 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_portal', '0002_auto_20201112_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('account_holder', models.CharField(max_length=128)),
                ('group_number', models.CharField(max_length=32)),
                ('account_number', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=32)),
                ('coverage', models.FloatField(default=0.0)),
                ('insurance_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PInsurance',
        ),
    ]
