# Generated by Django 3.1.2 on 2020-11-18 00:31

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xamine.models
import xamine.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ModalityOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField(default=1000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('visit_reason', models.CharField(max_length=128)),
                ('imaging_needed', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('imaged', models.CharField(blank=True, max_length=64, null=True)),
                ('imaged_time', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, max_length=5000, null=True)),
                ('completed', models.CharField(blank=True, max_length=64, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xamine.level')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xamine.modalityoption')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('radiologists', models.ManyToManyField(blank=True, related_name='radiol_teams', to=settings.AUTH_USER_MODEL)),
                ('technicians', models.ManyToManyField(blank=True, related_name='tech_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128)),
                ('email_info', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField(validators=[xamine.validators.check_past_date])),
                ('phone_number', models.CharField(max_length=32)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True)),
                ('allergy_asthma', models.BooleanField()),
                ('allergy_xraydye', models.BooleanField()),
                ('allergy_mridye', models.BooleanField()),
                ('allergy_latex', models.BooleanField()),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=256)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_keys', to='xamine.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='xamine.patient'),
        ),
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='xamine.team'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to=xamine.models.image_path, validators=[xamine.validators.validate_file_size])),
                ('user', models.CharField(max_length=30)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='xamine.order')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='xamine.order')),
                ('total', models.FloatField(default=0.0)),
                ('isPaid', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xamine.patient')),
            ],
        ),
    ]
