# Generated by Django 3.1.2 on 2020-10-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0039_auto_20200429_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalityoption',
            name='price',
            field=models.FloatField(default=1000.0),
        ),
    ]
