# Generated by Django 3.1.2 on 2020-11-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0043_auto_20201104_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
