# Generated by Django 3.1.2 on 2020-11-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0044_auto_20201104_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
