# Generated by Django 3.1.1 on 2020-11-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0045_auto_20201104_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Patient',
            new_name='patient',
        ),
    ]
