# Generated by Django 3.1.2 on 2020-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0045_auto_20201104_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
