# Generated by Django 3.1.2 on 2020-11-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0046_auto_20201104_1655'),
        ('xamine', '0045_auto_20201104_1442'),
    ]

    operations = [
    ]
