# Generated by Django 3.1.2 on 2020-11-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0047_merge_20201104_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Patient',
            new_name='patient',
        ),
    ]
