# Generated by Django 3.1.2 on 2020-11-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0050_auto_20201110_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
    ]
