# Generated by Django 3.1.1 on 2020-11-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0051_remove_patient_insurance'),
        ('xamine', '0046_auto_20201105_1931'),
    ]

    operations = [
    ]
